version: '3'

services:
    db:
        container_name: db
        build: ./requirements/mariadb/
        volumes:
            - ${PWD}/db_data:/var/lib/mysql
        networks:
          - nginx_network
        restart: always

    wordpress:
        container_name: wordpress
        build: ./requirements/wordpress/
        volumes:
            - ${PWD}/wp_data:/var/www/rvalton.42.fr
        environment:
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        networks:
            - nginx_network
        depends_on:
          - db
        restart: always

    nginx:
        container_name: nginx
        build: ./requirements/nginx/
        volumes:
            - ${PWD}/wp_data:/var/www/rvalton.42.fr
        ports:
            - "8080:8080"
        networks:
            - nginx_network
        depends_on:
          - wordpress
        restart: always

networks:
    nginx_network:
        name: nginx_network
        driver: bridge

volumes:
    wp_data:
        driver: local
        driver_opts:
            type: none
            device: ${PWD}/wp_data
            o: bind
    db_data:
        driver: local
        driver_opts:
          type: none
          device: ${PWD}/db_data
          o: bind
